apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-payment-service
  name: sakila-payment-service
spec:
  type: NodePort
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9000
      nodePort: 30002
  selector:
    sakila-service: sakila-payment-service
status:
  loadBalancer: {}
