version: '2.1'

networks:
  sakila-postgres-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.18.0.0/24
          ip_range: 176.18.0.0/24
          gateway: 176.18.0.254
  sakila-mongodb-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.18.1.0/24
          ip_range: 176.18.1.0/24
          gateway: 176.18.1.254
  sakila-backend-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.18.2.0/24
          ip_range: 176.18.2.0/24
          gateway: 176.18.2.254
  sakila-frontend-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.18.3.0/24
          ip_range: 176.18.3.0/24
          gateway: 176.18.3.254

services:
  sakila-zookeeper:
    image: com.example.sakila/sakila-zookeeper:1.0-SNAPSHOT
    container_name: sakila-zookeeper
    mem_limit: 512m
    networks:
      - sakila-backend-network
    ports:
      - 2181:2181
  sakila-kafka:
    image: com.example.sakila/sakila-kafka:1.0-SNAPSHOT
    container_name: sakila-kafka
    mem_limit: 512m
    depends_on:
      - sakila-zookeeper
    networks:
      - sakila-backend-network
    ports:
      - 9092:9092
      - 9093:9093
  sakila-postgres:
    image: com.example.sakila/sakila-postgres:1.0-SNAPSHOT
    container_name: sakila-postgres
    mem_limit: 512m
    networks:
      - sakila-postgres-network
    ports:
      - 5678:5432
  sakila-mongodb:
    image: com.example.sakila/sakila-mongodb:1.0-SNAPSHOT
    container_name: sakila-mongodb
    mem_limit: 512m
    networks:
      - sakila-mongodb-network
    ports:
      - 27777:27017
  sakila-discovery-service:
    image: com.example.sakila/sakila-discovery-service:1.0-SNAPSHOT
    container_name: sakila-discovery-service
    mem_limit: 512M
    networks:
      - sakila-backend-network
    ports:
      - 8761:8761
  sakila-api-gateway:
    image: com.example.sakila/sakila-api-gateway:1.0-SNAPSHOT
    container_name: sakila-api-gateway
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
    networks:
      - sakila-backend-network
      - sakila-frontend-network
    ports:
      - 8999:8999
    command: --spring.profiles.active=docker-secrets
  sakila-address-service:
    image: com.example.sakila/sakila-address-service:1.0-SNAPSHOT
    container_name: sakila-address-service
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
      - sakila-postgres
    networks:
      - sakila-backend-network
      - sakila-postgres-network
    command: --spring.profiles.active=docker-secrets
  sakila-film-service:
    image: com.example.sakila/sakila-film-service:1.0-SNAPSHOT
    container_name: sakila-film-service
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
      - sakila-mongodb
    networks:
      - sakila-backend-network
      - sakila-mongodb-network
    command: --spring.profiles.active=docker-secrets
  sakila-payment-service:
    image: com.example.sakila/sakila-payment-service:1.0-SNAPSHOT
    container_name: sakila-payment-service
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
      - sakila-postgres
    networks:
      - sakila-backend-network
      - sakila-postgres-network
    command: --spring.profiles.active=docker-secrets
  sakila-store-write-service:
    image: com.example.sakila/sakila-store-write-service:1.0-SNAPSHOT
    container_name: sakila-store-write-service
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
      - sakila-postgres
      - sakila-kafka
    networks:
      - sakila-backend-network
      - sakila-postgres-network
    command: --spring.profiles.active=docker-secrets
  sakila-store-read-service:
    image: com.example.sakila/sakila-store-read-service:1.0-SNAPSHOT
    container_name: sakila-store-read-service
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
      - sakila-store-write-service
      - sakila-postgres
      - sakila-kafka
    networks:
      - sakila-backend-network
      - sakila-postgres-network
    command: --spring.profiles.active=docker-secrets
  sakila-frontend:
    image: com.example.sakila/sakila-frontend:1.0-SNAPSHOT
    container_name: sakila-frontend
    mem_limit: 512M
    depends_on:
      - sakila-discovery-service
      - sakila-api-gateway
    networks:
      - sakila-frontend-network
    ports:
      - 80:80
