#!/bin/sh

declare -a components=("postgres" "mongodb" "zookeeper"
  "kafka" "discovery-service" "redis" "elastic-search"
  "api-gateway" "address-service" "film-service"
  "payment-service" "store-read-service"
  "store-write-service" "frontend")

echo 'Deploying sakila-microservices to kubernetes'
echo

echo 'Creating network policies'
kubectl apply -f ./kubernetes
echo

for component in "${components[@]}"
do
  component_name="sakila-${component}"
  kubernetes_dir="./${component_name}/kubernetes"

  echo "Deploying component '${component}' with kubernetes configuration from ${kubernetes_dir}"
  kubectl apply -f "${kubernetes_dir}"
  echo
done

echo 'Finished.'
echo
