#!/bin/sh

echo 'Deploying sakila-microservices to kubernetes'
echo

echo 'Creating network policies'
kubectl apply -f ./kubernetes
echo

echo 'Creating postgres db'
kubectl apply -f ./sakila-postgres/kubernetes
echo

echo 'Creating mongodb'
kubectl apply -f ./sakila-mongodb/kubernetes
echo

echo 'Creating zookeeper'
kubectl apply -f ./sakila-zookeeper/kubernetes
echo

echo 'Creating kafka'
kubectl apply -f ./sakila-kafka/kubernetes
echo

echo 'Creating discovery service'
kubectl apply -f ./sakila-discovery-service/kubernetes
echo

echo 'Creating redis server'
kubectl apply -f ./sakila-redis/kubernetes
echo

echo 'Creating API gateway'
kubectl apply -f ./sakila-api-gateway/kubernetes
echo

echo 'Creating sakila-address-service'
kubectl apply -f ./sakila-address-service/kubernetes
echo

echo 'Creating sakila-film-service'
kubectl apply -f ./sakila-film-service/kubernetes
echo

echo 'Creating sakila-payment-service'
kubectl apply -f ./sakila-payment-service/kubernetes
echo

echo 'Creating sakila-store-read-service'
kubectl apply -f ./sakila-store-read-service/kubernetes
echo

echo 'Creating sakila-store-write-service'
kubectl apply -f ./sakila-store-write-service/kubernetes
echo

echo 'Creating sakila-frontend'
kubectl apply -f ./sakila-frontend/kubernetes
echo

echo 'Finished.'
echo
