apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-kafka
  name: sakila-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9093"
      port: 9093
      targetPort: 9093
  selector:
    sakila-service: sakila-kafka
status:
  loadBalancer: {}
