CREATE USER sakila_address_service WITH
  ENCRYPTED PASSWORD 'sakila_dba_pass'
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

CREATE USER sakila_film_service WITH
  ENCRYPTED PASSWORD 'sakila_dba_pass'
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

CREATE USER sakila_payment_service WITH
  ENCRYPTED PASSWORD 'sakila_dba_pass'
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

CREATE USER sakila_store_read_service WITH
  ENCRYPTED PASSWORD 'sakila_dba_pass'
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

CREATE USER sakila_store_write_service WITH
  ENCRYPTED PASSWORD 'sakila_dba_pass'
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;
