apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-api-gateway
  name: sakila-api-gateway
spec:
  type: NodePort
  ports:
    - name: "8999"
      port: 8999
      targetPort: 8999
      nodePort: 30999
  selector:
    sakila-service: sakila-api-gateway
status:
  loadBalancer: {}
