apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-frontend
  name: sakila-frontend
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    sakila-service: sakila-frontend
status:
  loadBalancer: {}
