apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sakila-service: sakila-store-read-service
  name: sakila-store-read-service
spec:
  replicas: 1
  selector:
    matchLabels:
      sakila-service: sakila-store-read-service
  strategy: {}
  template:
    metadata:
      labels:
        backend-network: "true"
        postgres-network: "true"
        sakila-service: sakila-store-read-service
    spec:
      containers:
        - args:
            - --spring.profiles.active=docker-secrets
          image: com.example.sakila/sakila-store-read-service:1.0-SNAPSHOT
          name: sakila-store-read-service
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
status: {}
