apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-address-service
  name: sakila-address-service
spec:
  type: NodePort
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 30000
  selector:
    sakila-service: sakila-address-service
status:
  loadBalancer: {}
