apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-store-write-service
  name: sakila-store-write-service
spec:
  type: NodePort
  ports:
    - name: "9003"
      port: 9003
      targetPort: 9000
      nodePort: 30003
  selector:
    sakila-service: sakila-store-write-service
status:
  loadBalancer: {}
