apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-discovery-service
  name: sakila-discovery-service
spec:
  type: NodePort
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
      nodePort: 30761
  selector:
    sakila-service: sakila-discovery-service
status:
  loadBalancer: {}
