apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-zookeeper
  name: sakila-zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    sakila-service: sakila-zookeeper
status:
  loadBalancer: {}
