server:
  port: 8999
spring:
  application:
    name: sakila-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: sakila-film-service
          uri: lb://sakila-film-service
          predicates:
            - Path=/api/film/**
        - id: sakila-film-service
          uri: lb://sakila-address-service
          predicates:
            - Path=/api/address/**
        - id: sakila-payment-service
          uri: lb://sakila-payment-service
          predicates:
            - Path=/api/payment/**
        - id: sakila-store-service
          uri: lb://sakila-store-service
          predicates:
            - Path=/api/store/**
        - id: sakila-store-write-service
          uri: lb://sakila-store-write-service
          predicates:
            - Path=/api/store/write/**
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${secrets.eureka.server.url}
