server:
  port: 8999
spring:
  application:
    name: sakila-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sakila-film-service
          uri: lb://sakila-film-service
          predicates:
            - Path=/api/film/**
