apiVersion: v1
kind: Service
metadata:
  labels:
    sakila-service: sakila-redis
  name: sakila-redis
spec:
  type: NodePort
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    sakila-service: sakila-redis
status:
  loadBalancer: {}
