apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sakila-service: sakila-mongodb
  name: sakila-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      sakila-service: sakila-mongodb
  strategy: {}
  template:
    metadata:
      labels:
        mongodb-network: "true"
        sakila-service: sakila-mongodb
    spec:
      containers:
        - image: com.example.sakila/sakila-mongodb:1.0-SNAPSHOT
          name: sakila-mongodb
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "536870912"
      restartPolicy: Always
status: {}
